# This is a basic workflow to help you get started with Actions

name: CI



# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!


      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo "github.base_ref:${{ github.base_ref }}"
          echo "github.ref: ${{ github.ref }}"
          echo "github.head_ref: ${{ github.head_ref }}"
          echo "github.sha: ${{ github.sha }}"
          echo "github.event.pull_request.head.sha: ${{ github.event.pull_request.head.sha }}"

      - 
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: saheerb
          password: ${{ secrets.MY_TOKEN }}
          
      -
        name: Build docker containers
        uses: docker/build-push-action@v2
        id: docker_build_dev
        with:
          context: .
          platforms: linux/amd64
          push: true 
          file: ./Dockerfile
          tags: ghcr.io/saheerb/docker-test:latest
      
      - 
        name: Find DEV DOCKER DIGEST
        id: docker_info_dev
        run: |
          DIGEST=$(python ./utils.py -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} get-digest -r docker-test -t latest)
          echo "::set-output name=DIGEST::$DIGEST"
          echo "Docker DIGEST: $DIGEST"

      - 
        name: copy image
        id: copy
        run: |
          python ./utils.py -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} copy-image -r docker-test -t latest

